### ISSUE TITLE
role installs epel.repo

### ISSUE THREAD

**Issue by bbaassssiiee** [dockpack/base_nodejs#1]
The EPEL repo can be avoided so we could install a supported version of NodeJS on RHEL. So should rather use SoftwareTools on RHEL/Centos. EPEL is not available on some on-prem Satellite's due to that support issue.

**Comment by bbaassssiiee** [comment]
NodeJS is available from SoftwareTools, which can be added to Centos/RHEL with:

```
- name: install centos software collections
  package:
    name: centos-release-scl-rh
    state: present
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  when: collections_enabled|bool and ansible_distribution == 'CentOS'
  tags:
    - nodejs
    - base_nodejs

- name: enable rhel software collections
  command: "yum-config-manager --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
  when: collections_enabled|bool and ansible_distribution == 'RedHat'
  tags:
    - nodejs
    - base_nodejs
```
